Image Alighnment

original, translation,euclidean,affine,homography

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt 
import glob,math

Read template and scanned image

In [ ]:
# rial_f=cv2.imread("book.png",cv2.IMREAD_COLOR)
# print(rial_f.shape)
# rial_f_b=cv2.cvtColor(rial_f,cv2.COLOR_BGR2BGRA)
# print(rial_f_b)



(1086, 1448, 3)
[[[195 204 199 255]
  [203 209 206 255]
  [206 213 209 255]
  ...
  [ 28  46  57 255]
  [ 31  49  60 255]
  [ 31  50  59 255]]

 [[198 206 200 255]
  [201 206 202 255]
  [201 206 202 255]
  ...
  [ 29  46  56 255]
  [ 30  46  57 255]
  [ 29  45  56 255]]

 [[206 212 204 255]
  [203 208 203 255]
  [200 205 202 255]
  ...
  [ 27  45  54 255]
  [ 29  45  55 255]
  [ 29  46  55 255]]

 ...

 [[ 10  22  36 255]
  [  7  20  34 255]
  [  6  18  31 255]
  ...
  [ 83 106 121 255]
  [ 92 117 131 255]
  [ 90 112 129 255]]

 [[ 10  22  37 255]
  [  8  20  34 255]
  [  7  18  31 255]
  ...
  [ 48  63  80 255]
  [ 59  75  93 255]
  [ 68  87 105 255]]

 [[ 12  25  37 255]
  [  7  20  33 255]
  [ 10  22  35 255]
  ...
  [ 60  76  92 255]
  [ 63  80  97 255]
  [ 63  81  98 255]]]


Panorama


In [ ]:
# imagefiles=glob.glob("")

HDR imaging
